apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  ports:
    - port: 2000
      targetPort: 1500
  selector:
    app: frontend-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend-app
          image: frontend-app:latest
          imagePullPolicy: Never # workaround for local docker image to be laoded in kind cluster
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "256Mi"
              cpu: "0.5"
          ports:
            - containerPort: 1500
          env:
            - name: PYTHON_API_URL
              valueFrom:
                configMapKeyRef:
                  name: python-config
                  key: PYTHON_API_URL
            - name: JS_API_URL
              valueFrom:
                configMapKeyRef:
                  name: js-config
                  key: JS_API_URL
