apiVersion: v1
kind: Service
metadata:
  name: js-service
spec:
  ports:
    - port: 6000
      targetPort: 2000
  selector:
    app: js-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: js-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: js-api
  template:
    metadata:
      labels:
        app: js-api
    spec:
      containers:
        - name: js-api
          image: js-api:latest
          imagePullPolicy: Never # workaround for local docker image to be laoded in kind cluster
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "256Mi"
              cpu: "0.5"
          ports:
            - containerPort: 2000
          env:
            - name: MYSQL_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DB_NAME
