apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  ports:
    - port: 3000
      targetPort: 80
  selector:
    app: python-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
        - name: python-api
          image: python_api:latest
          imagePullPolicy: Never # workaround for local docker image to be laoded in kind cluster
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "256Mi"
              cpu: "0.5"
          ports:
            - containerPort: 80
          env:
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: MONGO_URL
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: DB_NAME
